version: '3'
services:
  hello-world:
    build: "./docker/go-develop"
    container_name: "hello-world"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/hello-world"
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ".:${GO_PROJECT_DIR}"
  todos-api:
    build: "./docker/go-develop"
    container_name: "todos-api"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/todos-api"
      PORT: 8081
    ports:
      - "8081:8081"
    volumes:
      - ".:${GO_PROJECT_DIR}"
  logger:
    build: "./docker/go-develop"
    container_name: "logger"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/logger"
    volumes:
      - ".:${GO_PROJECT_DIR}"
